//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Thumbnail { get; set; }
        public string IdCardNumber { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string TokenRegister { get; set; }
        public Nullable<System.DateTime> ExpireTokenRegister { get; set; }
        public string TokenLogin { get; set; }
        public Nullable<System.DateTime> ExpireTokenLogin { get; set; }
        public string TokenForgotPassword { get; set; }
        public Nullable<System.DateTime> ExpireTokenForgotPassword { get; set; }
        public Nullable<bool> IsAppove { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsVerifyEmail { get; set; }
        public Nullable<bool> IsVerifyPhone { get; set; }
        public Nullable<bool> IsBanned { get; set; }
        public Nullable<System.DateTime> DateBanned { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
