//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int ID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string CurrencyExchange { get; set; }
        public string ProductName { get; set; }
        public string SupplierPrice { get; set; }
        public string SelllingPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string TotalAmount { get; set; }
        public string TotalDiscount { get; set; }
        public string TotalPaid { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
