//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTransactionStatu
    {
        public int ID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> TransactionStatusID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserUpdate { get; set; }
        public string FullNameUserUpdate { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
    }
}
